### ISSUE TITLE
Can't find additional calendars via FindFolders

### ISSUE THREAD

**Issue by mkoegel** [gautamsi/ews-javascript-api#117]
Hi,

I try to get the FolderIds for additional calendars I created named "TestA" and "TestB".
Unfortunately I get a empty result:

```
FindFoldersResults {
   totalCount: 0,
   nextPageOffset: null,
   moreAvailable: false,
   folders: [] }
```
My code:
```
var config = require('config');
var ews = require('ews-javascript-api');
ews.EwsLogging.DebugLogEnabled = true;
var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2013);
exch.Credentials = new ews.ExchangeCredentials(config.get('security.u'), config.get('security.p'));
//set ews endpoint url to use
exch.Url = new ews.Uri(config.get('ews.url'));

var folderId = new ews.FolderId(ews.WellKnownFolderName.Calendar, new ews.Mailbox("me@example.com", "SMTP"));
var view = new ews.FolderView(10);
exch.FindFolders(folderId, view).done(
    function (res) { console.log(res); },
    function (errors) {
    console.log(errors); });

```

What am I doing wrong?

Also how would I create a filter that gives me a specific calendar?

`filter = new ews.SearchFilter.IsEqualTo(ews.FolderSchema.DisplayName.Name, "TestA");`
doesn't work.

**Comment by gautamsi** [comment]
is the additional calendar folder child of default Calendar folder or Root?
try this if it is root. 

```js
var config = require('config');
var ews = require('ews-javascript-api');
ews.EwsLogging.DebugLogEnabled = true;
var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2013);
exch.Credentials = new ews.ExchangeCredentials(config.get('security.u'), config.get('security.p'));
//set ews endpoint url to use
exch.Url = new ews.Uri(config.get('ews.url'));

var folderId = new ews.FolderId(ews.WellKnownFolderName.Root, new ews.Mailbox("me@example.com", "SMTP"));
var view = new ews.FolderView(10);
var filter = new ews.SearchFilter.IsEqualTo(ews.FolderSchema.FolderClass,"IPF.Appointment");
exch.FindFolders(folderId, filter, view).done(
    function (res) { console.log(res); },
    function (errors) {
    console.log(errors); });

```

**Comment by mkoegel** [comment]
Thanks for the quick response.
Works nice after adding those lines:
```
view.Traversal = ews.FolderTraversal.Deep;
view.PropertySet = ews.PropertySet.FirstClassProperties;

```
To find a single Folder by name I tried to combine the filters like this:
```
var filter1 = new ews.SearchFilter.IsEqualTo(ews.FolderSchema.FolderClass,"IPF.Appointment");
var filter2 = new ews.SearchFilter.IsEqualTo(ews.FolderSchema.DisplayName.Name, "TestA");
var filter = new ews.SearchFilter.SearchFilterCollection(ews.LogicalOperator.And, [filter1, filter2]);

```
but get the error

> TypeError: this.PropertyDefinition.WriteToXml is not a function

**Comment by gautamsi** [comment]
due to #96 , working on 0.6.2 release soon, fixing dependency update error, including TypeScript Update to 2.0.6.

**Comment by mkoegel** [comment]
Updated to 0.6.2, but still the same error.
Apparently it's already the DisplayName filter that fails. If I use just filter2 I get the error as well. Something wrong with that filter definition?

**Comment by gautamsi** [comment]
can you fix a typo and try again

`var filter2 = new ews.SearchFilter.IsEqualTo(ews.FolderSchema.DisplayName.Name, "TestA");`
to
`var filter2 = new ews.SearchFilter.IsEqualTo(ews.FolderSchema.DisplayName, "TestA");`

**Comment by mkoegel** [comment]
Thanks for your help. Works fine now.
